-- Add comprehensive paper metadata columns
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS year INTEGER DEFAULT NULL;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS authors JSONB DEFAULT NULL;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS venue TEXT DEFAULT NULL;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS abstract TEXT DEFAULT NULL;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS introduction TEXT DEFAULT NULL;
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS conclusion TEXT DEFAULT NULL;
