-- Seed journals table with sample data
INSERT INTO journals (name, description, impact_factor, h_index, is_open_access, publication_time_months, domain, url) VALUES
  ('Nature', 'Leading multidisciplinary science journal', 49.96, 1139, false, 3, 'Multidisciplinary', 'https://www.nature.com'),
  ('Science', 'Premier global science journal', 47.73, 1061, false, 3, 'Multidisciplinary', 'https://www.science.org'),
  ('Cell', 'Life sciences and biomedical research', 64.50, 456, false, 4, 'Life Sciences', 'https://www.cell.com'),
  ('The Lancet', 'Medical research and global health', 168.90, 567, false, 2, 'Medicine', 'https://www.thelancet.com'),
  ('NEJM', 'New England Journal of Medicine', 176.08, 678, false, 2, 'Medicine', 'https://www.nejm.org'),
  ('PLOS ONE', 'Open access multidisciplinary journal', 3.75, 389, true, 2, 'Multidisciplinary', 'https://journals.plos.org/plosone'),
  ('Nature Communications', 'Open access multidisciplinary', 16.60, 234, true, 3, 'Multidisciplinary', 'https://www.nature.com/ncomms'),
  ('Scientific Reports', 'Open access natural sciences', 4.99, 178, true, 2, 'Natural Sciences', 'https://www.nature.com/srep'),
  ('IEEE Access', 'Open access engineering and CS', 3.47, 89, true, 1, 'Engineering', 'https://ieeeaccess.ieee.org'),
  ('Frontiers in Psychology', 'Open access psychology', 3.80, 123, true, 3, 'Psychology', 'https://www.frontiersin.org/journals/psychology'),
  ('JAMA', 'Journal of the American Medical Association', 157.33, 567, false, 3, 'Medicine', 'https://jamanetwork.com'),
  ('BMJ', 'British Medical Journal', 105.72, 456, false, 2, 'Medicine', 'https://www.bmj.com'),
  ('Proceedings of the National Academy of Sciences', 'PNAS multidisciplinary', 11.20, 678, false, 2, 'Multidisciplinary', 'https://www.pnas.org'),
  ('Nature Medicine', 'Biomedical research', 87.24, 345, false, 4, 'Medicine', 'https://www.nature.com/nm'),
  ('Nature Biotechnology', 'Biotechnology research', 68.16, 289, false, 4, 'Biotechnology', 'https://www.nature.com/nbt'),
  ('Artificial Intelligence', 'AI research journal', 14.05, 156, false, 6, 'Computer Science', 'https://www.journals.elsevier.com/artificial-intelligence'),
  ('Journal of Machine Learning Research', 'ML research', 6.07, 234, true, 3, 'Computer Science', 'http://jmlr.org'),
  ('ACM Computing Surveys', 'Computer science surveys', 23.80, 178, false, 6, 'Computer Science', 'https://dl.acm.org/journal/csur'),
  ('IEEE Transactions on Pattern Analysis', 'PAMI computer vision', 24.31, 267, false, 5, 'Computer Science', 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=34'),
  ('Neuron', 'Neuroscience research', 16.20, 345, false, 3, 'Neuroscience', 'https://www.cell.com/neuron'),
  ('Nature Neuroscience', 'Neuroscience', 28.77, 289, false, 4, 'Neuroscience', 'https://www.nature.com/neuro'),
  ('Physical Review Letters', 'Physics research', 8.60, 567, false, 2, 'Physics', 'https://journals.aps.org/prl'),
  ('Nature Physics', 'Physics research', 19.68, 234, false, 4, 'Physics', 'https://www.nature.com/nphys'),
  ('Chemical Reviews', 'Chemistry reviews', 62.10, 456, false, 6, 'Chemistry', 'https://pubs.acs.org/journal/chreay'),
  ('Journal of the American Chemical Society', 'JACS chemistry', 16.38, 678, false, 3, 'Chemistry', 'https://pubs.acs.org/journal/jacsat'),
  ('Environmental Science & Technology', 'Environmental research', 11.36, 345, false, 3, 'Environmental Science', 'https://pubs.acs.org/journal/esthag'),
  ('Nature Climate Change', 'Climate science', 30.90, 178, false, 4, 'Environmental Science', 'https://www.nature.com/nclimate'),
  ('Ecology Letters', 'Ecology research', 9.14, 234, false, 3, 'Ecology', 'https://onlinelibrary.wiley.com/journal/14610248'),
  ('Trends in Ecology & Evolution', 'TREE ecology', 16.80, 289, false, 4, 'Ecology', 'https://www.cell.com/trends/ecology-evolution'),
  ('American Economic Review', 'Economics research', 10.70, 456, false, 6, 'Economics', 'https://www.aeaweb.org/journals/aer')
ON CONFLICT DO NOTHING;
